#!/bin/bash
# // Exporting Language to UTF-8
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'
export LC_CTYPE='en_US.utf8'

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CY='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

# // Exporting URL Host
export Server_URL="autosc.me/aio"
export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther="PREMIUM 2024"

function garis() {
echo -e "${CY}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

url_izin="https://raw.githubusercontent.com/daneshswara29/instalasi/main/register"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
checking_sc() {
useexp=$(wget -qO- $url_izin | grep $ipsaya | awk '{print $3}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
lane
echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          ${exitsc}"
lane
echo -e ""
echo -e "            \033[0;35mPERMISSION DENIED !${exitsc}"
echo -e "   ${j}Your VPS${exitsc} $ipsaya ${j}Has been Banned${exitsc}"
echo -e "     ${j}Buy access permissions for scripts${exitsc}"
echo -e "             ${j}Contact Admin :${exitsc}"
echo -e "      \033[0;36mWhatsapp${exitsc} wa.me/6282380835972"
lane
exit
fi
}
checking_sc


function create(){
clear

garis
echo -e "${GREEN}| \E[44;1;39m      NOOBZVPN  CREATE            \E[0m|"
garis
read -p "Username: " user
read -p "Password: " pass
read -p "Exp (0 for unlimited days):" exp
read -p "IP LIMIT " ip

if [ ! -e /etc/Dswara/limit/noobs/ip/ ]; then
  mkdir -p /etc/Dswara/limit/noobs/ip/
fi
echo "$ip" > /etc/Dswara/limit/noobs/ip/$user

noobzvpns --add-user $user $pass --expired-user $user $exp


clear

garis
echo -e "${CY}| \E[44;1;39m      NOOBZVPN'S ACCOUNT            \E[0m|"
garis
echo ""
echo -e "DOMAIN : $( cat /etc/xray/domain )"
echo -e "USERNAME: $user"
echo -e "PASSWORD: $pass"
echo -e "IP LIMIT: $ip"
echo -e "EXP DAYS: $exp DAYS"
echo -e "tcp_std port: 2052"
echo -e "tcp_ssl port: 2053"
garis
echo -e "Example config TCP_STD 2052"
garis
echo ""
echo -e "EN7O4DXAIyDVJrPpjPYKrQqo/GquMMlsriivwhce/oci7DAq0Yxz3IkWIZbmJP8GtkEXP3nlLBXmIiExeu8bVxT8PT2pz5bfUu1DWHVFh2bXFAIoerNst6vIwmSOpdtAiLOhZH6J8voH2b5ofrm/defIRgGBSmPFyCDenWY8esqcgYdOLSFrpdxcoAvMxvDKisrx5102imO/GhIiS58NZ40T/xZfosySVrStWGB92zMf13Zern6B4wn8n1eK69A6DtMXJwsdgLm13ahqjrxqiKjbbePnvoT6gyaRYQn6QOxzSC2yBawQjzuqSRPkfY23EXLS+iRV3SkxBnp/fpkU2adqIUh0cG5Pj2p5EQvUndGxQoUIp79WTfYvaeIZrBdk1NRBUInI/2GN1wIKvSRF4tmMsuTYPXlJ8fvNFcvvuYLPvx/o1ENH8UAB5Ajyl7s7j2yOwFPeTI5SYCXyj0P2A9nSAfEMpF6NE3jPSrIg38gLFNDcW9WSJwywe1RZNeN7hABFq8kdYCHSTZjNh/+3uEySkDyaxi7YPbdQVMxM9quBRbYgbx/4SxZ7WHmo6jcnjE/9q3IJ92YteLfDMgymSay+zlkiiodLOJAc1ns="
echo ""
garis
echo -e "Example config TCP_SSL 2053"
garis
echo ""

echo -e "EDfIwuHJdVRKJGSiQb0C/6yI9eY15qqrE1sHdos5f6iPGjjW144bOFTb1qpBjGn7XEwhXXafdBNLZkDUC42xdPN/5FMHqH82nhV4jlnZrY9OMRlpJQPfwDFkhmS5o72w1W6gvsz3liuAmgQbG/DCrrBNQ11qXXI/YGpBRX1yOgu4kmBAP4vQGL4jcRbynIOKYMmyrZz5Ph8C8sxO243LdhrmAA4+OuXeajlZIbGLtgJqN0+/1Hoik/ZqgVtBhOsJyL3YfNp1wrsbr6Y4QyTJIAVkvjcrD1Fhd95xiMLugjAnkkoLASIcJ2mp8TaBA7QuROeZNdwdml+1qqldoVhQbODtZMtE8FUL01Wz/9Np+Z8VUuqMqexDrSaD25i/O+0BdCLb/58Gt4+rkauOiNj8+w17+DZ6billHEN1UGP3FMiJWJyS1q8S4EIubO3xlebQzKHcKF631Rv1DtI7UyGlHDb/PTioDEg/PRxhSK/u5FUfBMM3lQWfBBxVvpELbm69xFJDqY7uGwjbrILw//duiNFQxCyMW6qGWZ2m3RSI/PXmjVJ8CjQMFyFMOUZWoOwzQCQkYcBiYZbWKOcunrvfEb+VjA=="
garis
echo -e "${GREEN}| \E[44;1;39m      PREMIUM 2024           \E[0m|"
garis
read -p "Enter Back To Menu"
m-noob
}

function delete(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S DELETE°            \E[0m|"
garis
read -p "username :" user

noobzvpns --remove-user $user
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S DELETED!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "Delete success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      PREMIUM 2024            \E[0m|"
garis
read -p "Enter Back To Menu"
m-noob
}


function renew(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S RENEW°            \E[0m|"
garis
read -p "username: " user
read -p "expired?: " exp
noobzvpns --renew-user $user --expired-user $user $exp
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S RENEW!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "renew success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      PREMIUM 2024            \E[0m|"
garis
read -p "Enter Back To Menu"
m-noob
}




function lock(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S LOCK°            \E[0m|"
garis
read -p "username: " user
noobzvpns --block-user $user
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S LOCK!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "locked success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      PREMIUM 2024            \E[0m|"
garis
read -p "Enter Back To Menu"
m-noob
}






function show(){

clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S MEMBER!°            \E[0m|"
garis
noobzvpns --info-all-user | awk '/^\s*\+.*-> active/ {gsub(/(issued\(yyyymmdd\)|hash_key): [0-9a-f]+/, ""); print; getline; print; getline; getline; getline; print; print "═══════════════════"}'

garis
echo -e "${GREEN} \E[44;1;39m      PREMIUM 2024            \E[0m"
garis
read -p "Enter Back To Menu"
m-noob
}



function unlock(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S UNLOCK°            \E[0m|"
garis
read -p "username: " user
noobzvpns --unblock-user $user
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S UNLOCK!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "unlocked success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      PREMIUM 2024            \E[0m|"
garis
read -p "Enter Back To Menu"
m-noob
}



function remove(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      NOOBZVPN'S UNLOCK            \E[0m|"
garis

read -p "Apakah Anda ingin menghapus semua user? (Y/N): " choice

if [ "$choice" == "Y" ] || [ "$choice" == "y" ]; then
    # Eksekusi perintah di sini
    echo "MENGHAPUS SEMUA USER!"
noobzvpns --remove-all-user
elif [ "$choice" == "N" ] || [ "$choice" == "n" ]; then
    echo "Membatalkan penghapusan."
menu-noobzvpns
else
    echo "Pilihan tidak valid."
fi

clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S UNLOCK!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "unlocked success!!"
garis
echo -e "${GREEN}| \E[44;1;39m     PREMIUM 2024            \E[0m|"
garis
read -p "Enter Back To Menu"
m-noob
}




clear
garis
echo -e "${GREEN} \E[44;1;39m     ALL MENU NOOBZVPN            \E[0m"
garis


echo -e "${LIGHT}"
echo -e "[01] CREATE ACCOUNT NOOBZVPNS"
echo -e "[02] DELETE ACCOUNT NOOBZVPNS"
echo -e "[03] RENEW ACCOUNT NOOBZVPNS"
echo -e "[04] LOCK ACCOUNT NOOBZVPNS"
echo -e "[05] UNLOCK ACCOUNT NOOBZVPNS"
echo -e "[06] SHOW ALL USER NOOBZVPNS"
echo -e "[07] REMOVE ALL USER NOOBZVPNS"
echo -e "[00] BACK TO MAIN MENU"
garis
echo -e "${GREEN} \E[44;1;39m            PREMIUM 2024            \E[0m"
garis
echo -e ""
echo
read -p " Select menu : " opt
echo -e ""
case $opt in
01 | 1) clear ; create ;;
02 | 2) clear ; delete ;;
03 | 3) clear ; renew ;;
04 | 4) clear ; lock ;;
05 | 5) clear ; unlock ;;
06 | 6) clear ; show ;;
07 | 7) clear ; remove ;;
00 | 0) clear ; menu ;;
*) clear ; menu ;;
esac